name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - android-latest
        arch:
          - x86_64
          - aarch64
          - armv7

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build binaries
        run: pyinstaller --onefile -n Master-${{ matrix.os }}-${{ matrix.arch }} Master.py

      - name: Archive binaries
        run: zip Master-${{ matrix.os }}-${{ matrix.arch }}.zip dist/Master-${{ matrix.os }}-${{ matrix.arch }}

      - name: Publish binaries
        uses: actions/upload-artifact@v3
        with:
          name: Master-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: Master-${{ matrix.os }}-${{ matrix.arch }}.zip

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            Master-${{ matrix.os }}-${{ matrix.arch }}.zip
